title: Global Calc Hub
description: Professional Precision Tools for Finance and Units.
url: "https://globalcalcpro.com"
baseurl: "" # חשוב מאוד: להשאיר ריק! האתר עכשיו בדומיין ראשי

permalink: /:title.html

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
