const fs = require('fs/promises');
const { google } = require('googleapis');

// Configuration Constants
const SITEMAP_PATH = './_site/sitemap.xml';
const INDEXING_SCOPE = ['https://www.googleapis.com/auth/indexing'];
const MAX_URLS_TO_PROCESS = 20; // Google allows up to 200 requests per day. We'll process the first 20.
const NOTIFICATION_TYPE = 'URL_UPDATED'; // Type of notification for new or updated pages

async function run() {
  console.log('🚀 Starting Google Indexing API process...');

  try {
    // 1. Retrieve the service account credentials from GitHub Secrets
    const credentials = JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT);

    // 2. Authenticate with Google API using JWT
    const jwtClient = new google.auth.JWT(
      credentials.client_email,
      null,
      credentials.private_key,
      INDEXING_SCOPE,
      null
    );

    await jwtClient.authorize();
    console.log('✅ Successfully authenticated with Google API.');

    // 3. Read the sitemap generated by Jekyll
    console.log(`🔎 Reading sitemap from: ${SITEMAP_PATH}`);
    const sitemap = await fs.readFile(SITEMAP_PATH, 'utf8');

    // 4. Extract all URLs from the sitemap
    const urls = [...sitemap.matchAll(/<loc>(.*?)<\/loc>/g)].map(m => m[1]);
    console.log(`Found ${urls.length} URLs in the sitemap.`);

    // Select a subset of URLs to send to Google to respect API quotas
    const targetUrls = urls.slice(0, MAX_URLS_TO_PROCESS);
    console.log(`Processing the first ${targetUrls.length} URLs for indexing.`);

    // 5. Send each URL to Google for indexing
    for (const url of targetUrls) {
      await google.indexing('v3').urlNotifications.publish({
        auth: jwtClient,
        requestBody: {
          url: url,
          type: NOTIFICATION_TYPE // Notifies Google that the page is new or updated
        }
      });
      console.log(`📡 Pinged Google to index: ${url}`);
    }

    console.log('🎉 Google Indexing API process complete! Google will crawl soon.');
  } catch (error) {
    console.error('❌ Error during Google Indexing API call:', error.message);
    // Optionally, rethrow the error if it should stop the CI/CD pipeline
    // throw error;
  }
}

run();